// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI266_EQcAGpFX4shH1Mb4aCnSGjMvfN0',
    appId: '1:1038163615534:web:1d940fd46027539e1824bf',
    messagingSenderId: '1038163615534',
    projectId: 'mobilprojesi-d67f5',
    authDomain: 'mobilprojesi-d67f5.firebaseapp.com',
    storageBucket: 'mobilprojesi-d67f5.firebasestorage.app',
    measurementId: 'G-28TPE8VW0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2qgXkXLJ4R6_KgTnNpX_p1s6p6YLu4xA',
    appId: '1:1038163615534:android:1d2deae186e4edab1824bf',
    messagingSenderId: '1038163615534',
    projectId: 'mobilprojesi-d67f5',
    storageBucket: 'mobilprojesi-d67f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLgUWN0f2INYOeT8qgJ5Qxh4vXK9GuIQc',
    appId: '1:1038163615534:ios:a69befaca3b945a51824bf',
    messagingSenderId: '1038163615534',
    projectId: 'mobilprojesi-d67f5',
    storageBucket: 'mobilprojesi-d67f5.firebasestorage.app',
    iosBundleId: 'com.example.akilliKampusa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLgUWN0f2INYOeT8qgJ5Qxh4vXK9GuIQc',
    appId: '1:1038163615534:ios:a69befaca3b945a51824bf',
    messagingSenderId: '1038163615534',
    projectId: 'mobilprojesi-d67f5',
    storageBucket: 'mobilprojesi-d67f5.firebasestorage.app',
    iosBundleId: 'com.example.akilliKampusa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI266_EQcAGpFX4shH1Mb4aCnSGjMvfN0',
    appId: '1:1038163615534:web:f7a0ff1f5cf0e2101824bf',
    messagingSenderId: '1038163615534',
    projectId: 'mobilprojesi-d67f5',
    authDomain: 'mobilprojesi-d67f5.firebaseapp.com',
    storageBucket: 'mobilprojesi-d67f5.firebasestorage.app',
    measurementId: 'G-WGWPCPPV68',
  );
}
